version: '2.0'
services:
  # builds lambda package
  build:
    image: softprops/lambda-rust:latest
    volumes:
    - .:/code
    - ~/.cargo/registry:/root/.cargo/registry
    environment:
    - BIN=relate-user-search-lambda