AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: User Search Rocket Lambda
Globals:
  Api:
    BinaryMediaTypes:
    - '*/*'
Resources:
  UserSearchRocketFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://relate-rocket-app-bucket/f1e6c021a03ac55254a6d0abc13faabb
      Handler: DUMMY
      Runtime: provided.al2023
      MemorySize: 128
      Events:
        Web:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        WebRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
